### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by SanekSemenov** [SanekSemenov/homepage#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by SanekOlol** [comment]
**Entrepreneurial Spirit**

- Embodies commitment, vision, calculated risk-taking and capacity for personal growth.
- Demonstrates perseverance in the face of adversity and to overcoming obstacles.
- Has learned from disappointing experiences.
- Relies on trusted individuals while showing ability to be an independent thinker and take risks in the face of uncertainty.

**Positive Energy**

Employees, colleagues, customers, and investors should feel energized being around a leader. Musk is highly charismatic with a positive outlook and optimism for a better future. This is inspirational and indubitably it has allowed him to persist through highly challenging circumstances in his businesses.

**Passion for Innovation**

Here is how we would define a leader with a passion for innovation

- Pioneers a new approach or technology.
- Recognizes business imperative of anticipating and embracing changes occurring in the competitive environment through continuous improvement in all aspects of the business.
- Creates a culture of innovation. Inspires others to keep up with the pace of change instead of staying with a day-late idea.
Many people would consider Musk to be the most innovative entrepreneur of our time. What’s amazing about him is that he seems to believe that there is an innovation to solve every problem that arises. He sees problems as opportunities and that is what has led him to his success

**Strategic Direction**

- Creates and turns vision into business realities.
- Builds and rebuilds the team’s commitment to the common goals.
- Demonstrates entrepreneurial maturity by building strategic alliances and surrounding him/herself with talented people—individuals, teams, the Board, and a range of advisers/allies to ensure success for all.
